/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as merchantGatewaySol from "./MerchantGateway.sol";
export type { merchantGatewaySol };
import type * as weppoSol from "./Weppo.sol";
export type { weppoSol };
import type * as mocks from "./mocks";
export type { mocks };
export type { WeppoForwarder } from "./WeppoForwarder";
