"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import {
    RiCheckboxCircleFill,
    RiErrorWarningFill,
    RiArrowRightSLine,
    RiWallet3Line,
    RiLineChartLine,
    RiExchangeBoxLine,
    RiHandCoinLine
} from "@remixicon/react";
import Link from "next/link";
import { GetStarted } from "./(components)/getStarted";

export default function Dashboard() {
    const [isIntegrated, setIsIntegrated] = useState<boolean | null>(null);
    const [agentCount, setAgentCount] = useState(0);

    useEffect(() => {
        async function checkIntegration() {
            const { data: { user } } = await supabase.auth.getUser();
            if (!user) {
                setIsIntegrated(false);
                return;
            }

            const { count, error } = await supabase
                .from('agents')
                .select('*', { count: 'exact', head: true })
                .eq('user_id', user.id);

            if (!error && count !== null && count > 0) {
                setIsIntegrated(true);
                setAgentCount(count);
            } else {
                setIsIntegrated(false);
            }
        }
        checkIntegration();
    }, []);

    console.log(isIntegrated);
    return (
        <div className="p-8 max-w-7xl mx-auto space-y-8 animate-in fade-in duration-700">
            {/* Header Section */}
            <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                <div>
                    <h1 className="text-3xl font-light tracking-tight text-white">Overview</h1>
                    <p className="text-neutral-400 mt-1">Monitor and manage your autonomous agent fleet.</p>
                </div>

                <div className="flex items-center gap-3  px-4 py-2 rounded-full">
                    <span className="text-xs font-medium text-neutral-300">System Status:</span>
                    {isIntegrated === null ? (
                        <div className="flex items-center gap-2">
                            <div className="w-2 h-2 rounded-full bg-neutral-600 animate-pulse" />
                            <span className="text-sm text-neutral-500 italic">Checking...</span>
                        </div>
                    ) : isIntegrated ? (
                        <div className="flex items-center gap-2">
                            <RiCheckboxCircleFill className="w-4 h-4 text-green-500" />
                            <span className="text-sm text-green-500 tracking-wide">Integrated</span>
                        </div>
                    ) : (
                        <div className="flex items-center gap-2">
                            <RiErrorWarningFill className="w-4 h-4 text-red-500" />
                            <span className="text-sm text-red-500 tracking-wide">not integrated</span>
                        </div>
                    )}
                </div>
            </div>

            {/* Quick Stats Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                <StatCard
                    title="Treasury Balance"
                    value="0.00 USD"
                    icon={<RiWallet3Line className="w-5 h-5" />}
                    description="Total funds across all agent wallets"
                />
                <StatCard
                    title="Monthly Revenue"
                    value="0.00 USD"
                    icon={<RiLineChartLine className="w-5 h-5" />}
                    description="MRR generated by your agents"
                />
                <StatCard
                    title="Monetized Endpoints"
                    value="0"
                    icon={<RiExchangeBoxLine className="w-5 h-5" />}
                    description="Active x402 monetization layers"
                />
                <StatCard
                    title="Total Spent"
                    value="0.00 USD"
                    icon={<RiHandCoinLine className="w-5 h-5" />}
                    description="Sub-task costs and operational expenses"
                />
            </div>

            {/* Get Started — show when not yet integrated */}
            <div className="bg-neutral-900/30 border border-neutral-800 rounded-2xl p-6">
                <GetStarted />
            </div>

            {/* Transaction Feed Placeholder */}
            <div className="bg-neutral-900/30 overflow-hidden">
                <div className="p-6 border-b border-neutral-800 flex items-center justify-between">
                    <h2 className="text-sm text-white">Recent Activity</h2>
                    <Link href="/dashboard/tracking" className="text-sm text-neutral-400 hover:text-white flex items-center gap-1 transition-colors">
                        View All Tracking <RiArrowRightSLine className="w-4 h-4" />
                    </Link>
                </div>
                <div className="p-12 text-center space-y-3">
                    <RiExchangeBoxLine className="w-10 h-10 text-neutral-700 mx-auto" />
                    <p className="text-neutral-500 max-w-sm mx-auto">
                        No transactions found. Once your agents start interacting, you'll see Sell/Buy logs here.
                    </p>
                </div>
            </div>
        </div>
    );
}

function StatCard({ title, value, icon, description }: { title: string, value: string, icon: React.ReactNode, description: string }) {
    return (
        <div className="bg-transparent p-6  space-y-4  transition-colors shadow-sm group">
            <div>
                <p className="text-sm text-neutral-400 font-">{title}</p>
                <div className="flex items-baseline gap-2 mt-1">
                    <span className="text-2xl text-white">{value}</span>
                </div>
                <p className="text-xs text-neutral-500 mt-2">{description}</p>
            </div>
        </div>
    );
}